"""empty message

Revision ID: 098abe9f6a7e
Revises: 1b6e43eb16a9
Create Date: 2020-08-21 19:06:50.121667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098abe9f6a7e'
down_revision = '1b6e43eb16a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
